services:
  ova-service:
    image: nicoguti0625/ova-service:latest
    container_name: ova-service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_USER=userdb
      - DB_PASS=passdb
      - JPA_DDL=create-drop
      - DB_HOST=jdbc:postgresql://db:5432/curso_springboot
    networks:
      - mynetwork

  lib-costos5:
        image: 'juandiiego2111/costos-jni:latest'
        ports:
          - '8083:8080'
        networks:
          - red-backend-app
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
